@baseUrl = http://192.168.130.142:3001/
@arenaId = 0004-UC56

###
GET {{baseUrl}}public-arenas

###
GET {{baseUrl}}arena/{{arenaId}}/settings

###
POST {{baseUrl}}arena/create
Content-Type: application/json

{
    "arenaType": "development",
    "countdownToStart": 30,
    "gameLength": 15000
}

###
POST {{baseUrl}}arena/{{arenaId}}/create-players
Content-Type: application/json

{
    "sharkNames": ["foo"]
}

###
POST {{baseUrl}}create-arena
ContentType: application/json

{
    "arenaType": "private",
    "countdownToStart": 10,
    "gameLength": 15000,
    "players": [ { "sharkName": "iiil;qr" } ]
}

### 
POST {{baseUrl}}create-arena
content-type: application/json 

{ 
    "arenaType": "private",
    "countdownToStart": 1,
    "gameLength": 15000,
    "players": [ { "sharkName": "zach" } ] }

###
POST {{baseUrl}}create-public-player/0002-16X6
Content-Type: application/json

{
    "sharkName": "iiilq;r"
}